# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
# *  CLASS input parameter file  *
# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

# This example of input file, intended for CLASS beginners, lists only
# the most common input parameters with small comments. Only lines
# containing an equal sign not preceded by a sharp sign "#" are considered by
# the code, any other line is considered as a comment.
#
# The normal syntax is:      parameter = value(s)


# -------------------------
# ----> General parameters:
# -------------------------

# REQUESTED OUTPUT FROM CLASS (Important!)
#  - 'tCl' for temperature Cls,
#  - 'pCl' for polarization (TE,BB,EE) Cls,
#  - 'lCl' for CMB lensing POTENTIAL Cl (Cl^psi-psi, required for lensed Cls),
#  - 'nCl' (or 'dCl') for density number count Cls,
#  - 'sCl' for galaxy lensing potential Cls (Cl^phi-phi),
#  - 'mPk' for total matter power spectrum P(k),
#  - 'dTk' for density transfer functions,
#  - 'vTk' for velocity transfer functions,
#  - 'Sd' for spectral distortions
#        --> deflection d: Cl^dd = l(l+1) C_l^phi-phi
#        --> convergence kappa and shear gamma: the share the same harmonic
#            power spectrum: Cl^gamma-gamma = 1/4 * [(l+2)!/(l-2)!] C_l^phi-phi
output = mPk
               # CMB l pivot of lensing

non_linear = oneloopPT            # Select 'halofit' or 'HMCode' or leave blank

ic = ad                           # Select initial conditions
#(ad,bi,cdi,nid,nvi) -> (adiabatic,baryon,cdm,neutrino density,neutrino velocity)
modes = s                         # Modes of the perturbations
# (s,v,t) -> (scalar,vector,tensor)

#Azadeh input
accurate_lensing = 1
T_cmb = 2.7255
m_ncdm = 0.1
w = -1
Omega_b = 0.04886698938 # 0.02247 / h^2
N_eff = 3.046
Omega_cdm = 0.25929733618 # 0.11923 / h^2
YHe = 0.24
tau_reio = 0.0568
k_pivot = 0.05
A_s = 2.1085e-9
ns = 0.96824


P_k_max_1/Mpc = 200                # Maximum k for P(k) in 1/Mpc
#P_k_max_1/Mpc = 2.              # Maximum k for P(k) in h/Mpc
z_pk = 0., 1.2, 3.5                # Redshifts of P(k,z)

# ----------------------------
# ----> Cosmological parameters:
# ----------------------------

h = 0.67810                       # Dimensionless reduced Hubble parameter (H_0 / (100km/s/Mpc))

has_rsd = yes

eft_compute_loop_matrices = yes
eft_write_loop_matrices = no
eft_direct_integration = no

# ----------------------------------
# ----> Output parameters:
# ----------------------------------

#root = output/default            # Root name of output files
overwrite_root = yes               # Overwrite the output files?
write_background = no             # Write background parameter table
write_thermodynamics = no         # Write thermodynamics parameter table
#k_output_values = 1e-3,1e-2      # Write perturbations parameter table (at given k)
write_primordial = no             # Write primordial parameter table
write_parameters = yeap           # Write used/unused parameter files
write_warnings = yes              # Warn about forgotten/wrong inputs

#Verbosity
input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 3
eft_verbose = 4
lensing_verbose = 1
output_verbose = 1
